// @ts-check
import { existsSync, writeFileSync, rmSync } from 'fs';
import { resolve, relative } from 'path';
import { _readCached } from './source-cache.js';
import { _findLiveFiles } from './codegen-registry.js';
import { _warnUnsafeExports } from './scanner.js';
import { _extractFunctionSignature, _extractFunctionSignatureFor, _extractErrorCodes, _isDynamicExport, _extractStreamReturnType, _extractDynamicFactoryParams } from './extract-types.js';
import { _extractAggregateWindows, _extractMultiplayerInfo } from './extract-options.js';
import { LIVE_EXPORT_RE, VALIDATED_EXPORT_RE, STREAM_EXPORT_RE, GUARD_EXPORT_RE, DYNAMIC_STREAM_RE, CRON_EXPORT_RE, BINARY_EXPORT_RE, UPLOAD_EXPORT_RE, DERIVED_EXPORT_RE, DYNAMIC_DERIVED_RE, ROOM_EXPORT_RE, MULTIPLAYER_EXPORT_RE, SMOOTH_EXPORT_RE, DOC_EXPORT_RE, WEBHOOK_EXPORT_RE, WEBHOOK_INBOUND_EXPORT_RE, WEBHOOK_OUTBOUND_EXPORT_RE, CHANNEL_EXPORT_RE, DYNAMIC_CHANNEL_RE, RATE_LIMIT_EXPORT_RE, EFFECT_EXPORT_RE, AGGREGATE_EXPORT_RE, FLAG_EXPORT_RE, LOCK_EXPORT_RE, PUBLIC_EXPORT_RE, PUBLIC_COMMENT_RE, IDEMPOTENT_EXPORT_RE, VOLATILE_EXPORT_RE } from './patterns.js';

/**
 * Generate and write type declarations for all $live/ modules.
 * Creates `$types.d.ts` in the live directory with ambient module declarations.
 * @param {string} liveDir
 * @param {string} dir
 */
export function _writeTypeDeclarations(liveDir, dir) {
	const typesPath = resolve(liveDir, '$types.d.ts');
	const content = _generateTypeDeclarations(liveDir, dir);
	if (content) {
		writeFileSync(typesPath, content);
	} else if (existsSync(typesPath)) {
		// Remove stale declarations when all live modules are deleted
		try { rmSync(typesPath); } catch {}
	}
}

/**
 * Generate ambient module declarations for all $live/ modules.
 * For TS files, attempts to extract real parameter/return types.
 * For JS files, falls back to `any`.
 * @param {string} liveDir
 * @param {string} dir
 * @returns {string}
 */
export function _generateTypeDeclarations(liveDir, dir) {
	if (!existsSync(liveDir)) return '';

	const files = _findLiveFiles(liveDir);
	if (files.length === 0) return '';

	const declarations = [
		'// Auto-generated by svelte-realtime - do not edit',
		'// Provides client-side types for $live/ imports',
		''
	];

	for (const filePath of files) {
		const rel = relative(liveDir, filePath).replace(/\\/g, '/').replace(/\.[jt]s$/, '');
		const source = _readCached(filePath);
		const isTS = filePath.endsWith('.ts');

		/** @type {string[]} */
		const exports = [];
		/** @type {Set<string>} */
		const handledNames = new Set();
		let needsStreamStore = false;
		let needsRpcError = false;
		let needsUploadHandle = false;

		// Detect live() exports
		let match;
		LIVE_EXPORT_RE.lastIndex = 0;
		while ((match = LIVE_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (isTS) {
				const sig = _extractFunctionSignature(source, name);
				exports.push(`  export const ${name}: ${sig};`);
			} else {
				exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
			}
		}

		// Detect live.validated() exports - extract real types for TS
		VALIDATED_EXPORT_RE.lastIndex = 0;
		while ((match = VALIDATED_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			// Only add if not already detected by LIVE_EXPORT_RE
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				if (isTS) {
					const sig = _extractFunctionSignatureFor(source, name, 'live\\.validated', 1);
					exports.push(`  export const ${name}: ${sig};`);
				} else {
					exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
				}
			}
		}

		// Extract thrown LiveError codes for typed error unions
		const errorCodes = _extractErrorCodes(source);
		if (errorCodes.length > 0) {
			needsRpcError = true;
			const union = errorCodes.map(c => `'${c}'`).join(' | ');
			exports.push(`  export type ErrorCode = ${union};`);
		}

		// Detect live.stream() exports
		STREAM_EXPORT_RE.lastIndex = 0;
		while ((match = STREAM_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			needsStreamStore = true;
			needsRpcError = true;
			const isDynamic = _isDynamicExport(source, name, 'live\\.stream');
			if (isTS) {
				const returnType = _extractStreamReturnType(source, name);
				const storeType = `StreamStore<${returnType} | undefined | { error: RpcError }>`;
				const loadSig = `{ load(platform: any, options?: { args?: any[]; user?: any }): Promise<${returnType}> }`;
				if (isDynamic) {
					const factoryParams = _extractDynamicFactoryParams(source, name, 'live\\.stream');
					exports.push(`  export const ${name}: (${factoryParams} => ${storeType}) & ${loadSig};`);
				} else {
					exports.push(`  export const ${name}: ${storeType} & ${loadSig};`);
				}
			} else {
				const loadSig = `{ load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> }`;
				if (isDynamic) {
					exports.push(`  export const ${name}: ((...args: any[]) => StreamStore<any>) & ${loadSig};`);
				} else {
					exports.push(`  export const ${name}: StreamStore<any> & ${loadSig};`);
				}
			}
		}

		// Detect live.channel() exports (same shape as streams)
		CHANNEL_EXPORT_RE.lastIndex = 0;
		while ((match = CHANNEL_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				const isDynamic = _isDynamicExport(source, name, 'live\\.channel');
				const loadSig = `{ load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> }`;
				if (isDynamic) {
					if (isTS) {
						const factoryParams = _extractDynamicFactoryParams(source, name, 'live\\.channel');
						exports.push(`  export const ${name}: (${factoryParams} => StreamStore<any>) & ${loadSig};`);
					} else {
						exports.push(`  export const ${name}: ((...args: any[]) => StreamStore<any>) & ${loadSig};`);
					}
				} else {
					exports.push(`  export const ${name}: StreamStore<any> & ${loadSig};`);
				}
			}
		}

		// Detect live.derived() exports (read-only stream, static or dynamic)
		DERIVED_EXPORT_RE.lastIndex = 0;
		while ((match = DERIVED_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				const isDynamic = _isDynamicExport(source, name, 'live\\.derived');
				const loadSig = `{ load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> }`;
				if (isDynamic) {
					if (isTS) {
						const factoryParams = _extractDynamicFactoryParams(source, name, 'live\\.derived');
						exports.push(`  export const ${name}: (${factoryParams} => StreamStore<any>) & ${loadSig};`);
					} else {
						exports.push(`  export const ${name}: ((...args: any[]) => StreamStore<any>) & ${loadSig};`);
					}
				} else {
					exports.push(`  export const ${name}: StreamStore<any> & ${loadSig};`);
				}
			}
		}

		// Detect live.aggregate() exports (read-only stream)
		AGGREGATE_EXPORT_RE.lastIndex = 0;
		while ((match = AGGREGATE_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				const windowKeys = _extractAggregateWindows(source, name);
				if (windowKeys && windowKeys.length > 0) {
					// Windowed: emit a namespace shape with one StreamStore
					// per window. Each window has its own .load(platform).
					const memberLines = windowKeys.map(wn =>
						`    ${JSON.stringify(wn)}: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };`
					).join('\n');
					exports.push(`  export const ${name}: {\n${memberLines}\n  };`);
				} else {
					exports.push(`  export const ${name}: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };`);
				}
			}
		}

		// Detect live.flag() exports (readable set-merge stream)
		FLAG_EXPORT_RE.lastIndex = 0;
		while ((match = FLAG_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				exports.push(`  export const ${name}: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };`);
			}
		}

		// Detect live.binary() exports
		BINARY_EXPORT_RE.lastIndex = 0;
		while ((match = BINARY_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				exports.push(`  export const ${name}: (buffer: ArrayBuffer | ArrayBufferView, ...args: any[]) => Promise<any>;`);
			}
		}

		// Detect live.upload() exports
		UPLOAD_EXPORT_RE.lastIndex = 0;
		while ((match = UPLOAD_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsUploadHandle = true;
				exports.push(`  export const ${name}: (source: Blob | ArrayBuffer | ArrayBufferView | ReadableStream<Uint8Array>, ...args: any[]) => UploadHandle<any>;`);
			}
		}

		// Detect live.rateLimit() exports - extract real types for TS
		RATE_LIMIT_EXPORT_RE.lastIndex = 0;
		while ((match = RATE_LIMIT_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				if (isTS) {
					const sig = _extractFunctionSignatureFor(source, name, 'live\\.rateLimit', 1);
					exports.push(`  export const ${name}: ${sig};`);
				} else {
					exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
				}
			}
		}

		// Detect live.lock() exports - the inner handler is the second arg of
		// live.lock(keyOrConfig, fn), so the function-signature extractor
		// reads from arg index 1.
		LOCK_EXPORT_RE.lastIndex = 0;
		while ((match = LOCK_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				if (isTS) {
					const sig = _extractFunctionSignatureFor(source, name, 'live\\.lock', 1);
					exports.push(`  export const ${name}: ${sig};`);
				} else {
					exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
				}
			}
		}

		// Detect live.idempotent() exports - inner handler at arg index 1.
		IDEMPOTENT_EXPORT_RE.lastIndex = 0;
		while ((match = IDEMPOTENT_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				if (isTS) {
					const sig = _extractFunctionSignatureFor(source, name, 'live\\.idempotent', 1);
					exports.push(`  export const ${name}: ${sig};`);
				} else {
					exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
				}
			}
		}

		// Detect live.volatile() exports - inner handler at arg index 0
		// (same shape as plain live()). The .fireAndForget(...) method is
		// attached by the __rpc(...) factory itself, so the generated stub
		// types as the plain RPC signature; users get the method at runtime.
		VOLATILE_EXPORT_RE.lastIndex = 0;
		while ((match = VOLATILE_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				if (isTS) {
					const sig = _extractFunctionSignatureFor(source, name, 'live\\.volatile', 0);
					exports.push(`  export const ${name}: ${sig};`);
				} else {
					exports.push(`  export const ${name}: (...args: any[]) => Promise<any>;`);
				}
			}
		}

		// Detect live.smooth() exports - the namespace carries the send paths
		// and the smooth(...) factory returning the predicted view.
		SMOOTH_EXPORT_RE.lastIndex = 0;
		while ((match = SMOOTH_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				exports.push(`  export const ${name}: { status: import('svelte/store').Readable<string>, smooth: (...args: any[]) => import('svelte-realtime/smooth').SmoothEntity, [member: string]: any };`);
			}
		}

		// Detect CRDT document exports - the namespace carries the send paths
		// and a factory (named after the kind) returning the replica view.
		DOC_EXPORT_RE.lastIndex = 0;
		while ((match = DOC_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			const kind = match[2];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				const viewType = kind === 'doc' ? 'DocHandle' : kind === 'map' ? 'DocMap' : 'DocList';
				exports.push(`  export const ${name}: { status: import('svelte/store').Readable<string>, ${kind}: (...args: any[]) => import('svelte-realtime/doc').${viewType}, [member: string]: any };`);
			}
		}

		// Detect live.multiplayer() exports - the room namespace plus the
		// connection-status view and the cursor methods. Runs before the room
		// branch and claims the name so the room branch skips it.
		MULTIPLAYER_EXPORT_RE.lastIndex = 0;
		while ((match = MULTIPLAYER_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				const mpInfo = _extractMultiplayerInfo(source, name);
				const rosterMembers = (mpInfo.hasPresence || mpInfo.hasCursors)
					? `, identify: (key: string) => void, room: (...args: any[]) => import('svelte-realtime/multiplayer').MultiplayerRoom`
					: '';
				exports.push(`  export const ${name}: { data: (...args: any[]) => StreamStore<any>, presence?: (...args: any[]) => StreamStore<any>, cursors?: (...args: any[]) => StreamStore<any>, status: import('svelte/store').Readable<string>, move: (...args: any[]) => void, reportViewport: (...args: any[]) => void${rosterMembers}, [action: string]: any };`);
			}
		}

		// Detect live.room() exports
		ROOM_EXPORT_RE.lastIndex = 0;
		while ((match = ROOM_EXPORT_RE.exec(source)) !== null) {
			const name = match[1];
			handledNames.add(name);
			if (!exports.some(e => e.includes(`export const ${name}:`))) {
				needsStreamStore = true;
				exports.push(`  export const ${name}: { data: (...args: any[]) => StreamStore<any>, presence?: (...args: any[]) => StreamStore<any>, cursors?: (...args: any[]) => StreamStore<any>, [action: string]: (...args: any[]) => Promise<any> | ((...args: any[]) => StreamStore<any>) };`);
			}
		}

		// Warn about exports with non-path-safe names (after all valid names collected)
		_warnUnsafeExports(source, `${dir}/${rel}`, handledNames);

		if (exports.length > 0) {
			declarations.push(`declare module '$live/${rel}' {`);
			if (needsStreamStore || needsRpcError || needsUploadHandle) {
				const clientImports = [];
				if (needsStreamStore) clientImports.push('StreamStore');
				if (needsRpcError) clientImports.push('RpcError');
				if (needsUploadHandle) clientImports.push('UploadHandle');
				declarations.push(`  import type { ${clientImports.join(', ')} } from 'svelte-realtime/client';`);
			}
			declarations.push(`  import type { Readable } from 'svelte/store';`);
			if (needsStreamStore || needsRpcError || needsUploadHandle) {
				declarations.push('');
			}
			declarations.push(...exports);
			declarations.push(`  export const empty: Readable<undefined>;`);
			declarations.push('}');
			declarations.push('');
		}
	}

	return declarations.join('\n');
}
