// Auto-generated by svelte-realtime -- do not edit
// Provides client-side types for $live/ imports

declare module '$live/auth' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const whoami: (...args: any[]) => Promise<any>;
  export const sendToInbox: (...args: any[]) => Promise<any>;
  export const adminAction: (...args: any[]) => Promise<any>;
  export const resetAuth: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN';
  export const inbox: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/channels' {
  import type { StreamStore } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const sendToLobby: (...args: any[]) => Promise<any>;
  export const joinRoster: (...args: any[]) => Promise<any>;
  export const sendToRoom: (...args: any[]) => Promise<any>;
  export const resetChannels: (...args: any[]) => Promise<any>;
  export const lobby: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const roster: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const room: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/cronjobs' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const tickNow: (...args: any[]) => Promise<any>;
  export const getCounts: (...args: any[]) => Promise<any>;
  export const resetCron: (...args: any[]) => Promise<any>;
  export const stats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const feed: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/cursor' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const moveCursor: (...args: any[]) => Promise<any>;
  export const removeCursor: (...args: any[]) => Promise<any>;
  export const resetCursor: (...args: any[]) => Promise<any>;
  export const cursors: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/derived' {
  import type { StreamStore } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const incOrders: (...args: any[]) => Promise<any>;
  export const incUsers: (...args: any[]) => Promise<any>;
  export const incOrdersBurst: (...args: any[]) => Promise<any>;
  export const publishOrgSource: (...args: any[]) => Promise<any>;
  export const getRecomputeCounts: (...args: any[]) => Promise<any>;
  export const resetDerived: (...args: any[]) => Promise<any>;
  export const dashboardStats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const debouncedStats: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const orgStats: ((...args: any[]) => StreamStore<any>) & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/echo' {
  import type { Readable } from 'svelte/store';
  export const echo: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/lock' {
  import type { Readable } from 'svelte/store';
  export const readLog: (...args: any[]) => Promise<any>;
  export const resetLog: (...args: any[]) => Promise<any>;
  export const ordered: (...args: any[]) => Promise<any>;
  export const bounded: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/presence' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const joinPresence: (...args: any[]) => Promise<any>;
  export const leavePresence: (...args: any[]) => Promise<any>;
  export const resetPresence: (...args: any[]) => Promise<any>;
  export const presence: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/room' {
  import type { StreamStore } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const setCursor: (...args: any[]) => Promise<any>;
  export const board: { data: (...args: any[]) => StreamStore<any>, presence?: (...args: any[]) => StreamStore<any>, cursors?: (...args: any[]) => StreamStore<any>, [action: string]: (...args: any[]) => Promise<any> | ((...args: any[]) => StreamStore<any>) };
  export const empty: Readable<undefined>;
}

declare module '$live/schema' {
  import type { Readable } from 'svelte/store';
  export const submitForm: (...args: any[]) => Promise<any>;
  export const submitNested: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/todos' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const ok: (...args: any[]) => Promise<any>;
  export const okWithPublish: (...args: any[]) => Promise<any>;
  export const fail: (...args: any[]) => Promise<any>;
  export const block: (...args: any[]) => Promise<any>;
  export const release: (...args: any[]) => Promise<any>;
  export const publishExternal: (...args: any[]) => Promise<any>;
  export const killSelf: (...args: any[]) => Promise<any>;
  export const reset: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'TEST_FAIL';
  export const todos: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}
