// Auto-generated by svelte-realtime -- do not edit
// Provides client-side types for $live/ imports

declare module '$live/echo' {
  import type { Readable } from 'svelte/store';
  export const echo: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/lock' {
  import type { Readable } from 'svelte/store';
  export const readLog: (...args: any[]) => Promise<any>;
  export const resetLog: (...args: any[]) => Promise<any>;
  export const ordered: (...args: any[]) => Promise<any>;
  export const bounded: (...args: any[]) => Promise<any>;
  export const empty: Readable<undefined>;
}

declare module '$live/todos' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const ok: (...args: any[]) => Promise<any>;
  export const okWithPublish: (...args: any[]) => Promise<any>;
  export const fail: (...args: any[]) => Promise<any>;
  export const block: (...args: any[]) => Promise<any>;
  export const release: (...args: any[]) => Promise<any>;
  export const publishExternal: (...args: any[]) => Promise<any>;
  export const reset: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'TEST_FAIL';
  export const todos: StreamStore<any> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}
